name:  Deploy website on push MASTER!

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copiar credenciales al archivo config
        run: |
          touch application/config/config.php
          echo -e "${{ secrets.CONFIG_TEST }}" > application/config/config.php

      - name: Copiar credenciales al archivo database
        run: |
          touch application/config/database.php
          echo -e "${{ secrets.DATABASE_TEST }}" > application/config/database.php

      - name: Copy files via SSH key
        uses: appleboy/scp-action@master
        with:
          host: 104.198.134.0
          username: prohab
          key: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}
          source: "./"
          target: /mnt/data/aplicaciones/Prueba/maderascrm
          overwrite: true
